package arcade;

import java.awt.Image;
import java.awt.image.BufferedImage;

import javax.swing.JPanel;

public class Varibles extends JPanel{
	public String eat = "";
	String choice2 = "";
	public Image chicken;
	public Image characterspeaking;
	public int script = 0;
	public BufferedImage bakeing;
	public  BufferedImage tiles[];
	public int background;
	public Image intro;
	boolean start = false; 
	public int x = 189;
	public int y = 100;
	public int backgroundcheck = 0;
	public int earthchanspeaking = 0;
	//and the bx and by values became the characters
	public int bx = 500;
	public boolean stop = false;
	public boolean attackphase = false;
	public boolean abilitytomove = true;
	public boolean tutorial = true;
	public boolean changegame = false;
	public boolean Dokistarted = false;
	public boolean spikeup = true;
	public boolean bar;
	public boolean jump;
	public boolean changedirection1 = false;
	public boolean gonethroughportal1;
	public int checkthat = 1;
	public int by = 700;
	public int test = 50;
	public int test2 = 500;
	public int chrisxp = 0;
	public int jakexp = 0;
	public int Jakex = 600;
	public int Chrisx = 250;
	public int swordx = 260;
	public int Jakey = 300;
	public int Chrisy = 300;
	public int swordy = 200;
	public int checkChrisx;
	public int checkChrisy;
	public int checkJakey;
	public int checkJakex;
	public int checkAudreyy;
	public int checkAudreyx;
	public int Audreyx;
	public int choiceattack = 0;
	public int cursorx = 250;
	public int cursory = 700;
	public int mouseX;
	public int mouseY;
	public int gravity = 0;
	public int canusegravity = 0;
	public int rightleftjump = 0;
	public int entertimes = 0;
	public int characterspeaking3x = 580;
	public int characterspeaking3y = 250;
	public int characterspeaking4x = 780;
	public int characterspeaking4y = 250;
	public int characterspeaking2x = 20;
	public int characterspeaking2y = 250;
	public int chicken5y;
	public int chicken5x;
	public int xVelocity;
	public int yVelocity;
	public int xVelocity2;
	public int yVelocity2;
	public int characterx = 162;
	public int charactery = 708;
	public int monsterx = 1018;
	public int monstery = 204;
	public int monster2x  = 802;
	public int monster2y = 648;
	public int monster3x = 674;
	public int monster3y = 500;
	public int monster4x = 730;
	public int monster4y = 348;
	public int monsterxlimitl = monsterx - 80;
	public int monsterxlimit2l = monster2x - 80;
	public int monsterxlimit3l = monster3x - 80;
	public int monsterxlimit4l = monster4x - 80;
	public int monsterxlimitr = monsterx + 80;
	public int monsterxlimit2r = monster2x + 80;
	public int monsterxlimit3r = monster3x + 80;
	public int monsterxlimit4r = monster4x + 80;
	public int checkcharacterx;
	public int checkcharactery;
	public Image backround;
	public Image Chris;
	public Image Jake;
	public Image Audrey;
	public Image textbox;
	public Image Earthchan;
	public Image eartchpic;
	public Image cursor;
	public Image chrischaracter;
	public Image textbox2;
	public Image characterspeaking2;
	public Image characterspeaking3;
	public Image characterspeaking4;
    public Image sword;
    public Image background1;
    public Image character1;
    public Image monster;
    public Image monster2;
    public Image monster3;
    public Image monster4;
    public Image portal2;
    public void monstermove() {
   
    }
    
}
